### ISSUE TITLE
Load multiple documents

### ISSUE THREAD

**Issue by shaunc** [tanbro/pyyaml-include#11]
If I have one document such as (foo.yaml):
```
!include ./baz.yaml
!include ./baz.yaml
```
and baz.yaml looks like:
```
baz1: x
---
baz2: y
```
I would like this to be interpreted as:
```
baz1: x
---
baz2: y
---
baz1: x
---
baz2: y
```
Is there any way to achieve this? Currently, even if I use `load_all()` my current setup fails with error.

**Comment by tanbro** [comment]
The feature of multiple-documents is not supported in the library yet...

**Comment by tanbro** [comment]
I think it's not possible for the library.

Since :

1. the library load including files by a `pyYAML` **Constructor**, what loaded can be only inside a document.

1. Till now, the library loads an including `YAML` file with `yaml.load()`.
   Of course we can change it to `full_load()`, but still it can not make a *"Multi-Docs"*, it will return an iterable(convert to list?)

**Comment by shaunc** [comment]
Yes ... would seem to need a change in pyyaml so that the Constructor could return document(s), not document fragments. I guess I'll close. Thanks for looking into it.
